on:
  schedule:
    - cron: "0 9 * * *" # trigger at 9:00 AM every day
  workflow_dispatch:

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Ping app
        uses: ilammy/url-health-check@v1.6.1
        with:
          url: https://full-stack-open-pokedex-06vd.onrender.com/health
          timeout: 10
