on:
  schedule:
    - cron: "0 9 * * *" # trigger at 9:00 AM every day
  workflow_dispatch:

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Ping app
          run: |
            if curl -f https://full-stack-open-pokedex-06vd.onrender.com/health; then
              echo "App is up ✅"
            else
              echo "App is down ❌"
              exit 1
            fi
