name: hello

on:
  push:
    branches:
      - main

jobs:
  hello_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello!"

      - name: Print current date
        run: date

      - name: List files in current directory (long format)
        run: ls -l
