name: Deployment pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SKIP_RELEASE: ${{ github.event_name == 'push' && contains(join(github.event.commits.*.message, ' '), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Run unit tests
        run: npm test
      - name: Start dev server
        run: npm start &
      - name: Wait for frontend
        run: npx wait-on http://localhost:8080
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: npm run test:e2e
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && env.SKIP_RELEASE == 'false' }}
        run: |
          curl https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Discord notification
        if: ${{ github.event_name == 'push' && env.SKIP_RELEASE == 'false' }}
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          COMMIT_SHA: ${{ github.sha }}
          COMMIT_AUTHOR: ${{ github.actor }}
          REPO_NAME: ${{ github.repository }}
          JOB_STATUS: ${{ job.status }}
        run: |
          if [ "$JOB_STATUS" = "success" ]; then
            MESSAGE="✅ Build & deployment successful!\nRepository: $REPO_NAME\nCommit: $COMMIT_SHA"
          else
            MESSAGE="❌ Build failed!\nRepository: $REPO_NAME\nCommit: $COMMIT_SHA\nAuthor: $COMMIT_AUTHOR\nCheck workflow logs for details."
          fi
          
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"$MESSAGE\"}" \
               "$WEBHOOK_URL"


  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && env.SKIP_RELEASE == 'false' }}
        uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
